

kafka:
  group:
    id: mean-speed
  client:
    id: mean-speed
  bootstrap:
    servers: ${KAFKA_ENDPOINT:processing.envirocar.org:9092}

mean-speed:
  mapMatching:
    url: ${MSS_MAPMATCHING_ENDPOINT:https://processing.envirocar.org}

postgres:
  host: ${POSTGRES_HOST://localhost}
  port: ${POSTGRES_PORT:5432}
  dbname: ${POSTGRES_DBNAME:postgres}
  username: ${POSTGRES_USERNAME:postgres}
  password: ${POSTGRES_PASSWORD:postgres}
    