

kafka:
  group:
    id: mean-speed
  client:
    id: mean-speed
  bootstrap:
    servers: ${KAFKA_ENDPOINT:processing.envirocar.org:9092}

trackcount:
  mapMatching:
    url: https://processing.envirocar.org/
